version: 0.2
phases:
  install: 
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install redoc-cli -g
  build:
    commands:
      - redoc-cli bundle telephant-api-documentation.yml --options.theme.colors.primary.main=orange --output index.html
artifacts:
  files:
    - index.html
    - telephant-api-documentation.yml
  discard-paths: yes