version: 0.2
phases:
  install: 
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install redoc-cli -g
  build:
    commands:
      - redoc-cli bundle http://petstore.swagger.io/v2/swagger.json --output index.html
artifacts:
  files:
    - index.html
  discard-paths: yes