version: 0.2
phases:
  install: 
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install redoc-cli -g
  build:
    commands: 
      - redoc-cli bundle telephant-api-documentation.yml --options '{"disable-search"}' --output index.html
artifacts:
  files:
    - index.html
    - telephant-api-documentation.yml
    - telephant-documentation-logo.jpg
  discard-paths: yes
