version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 8
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install redoc-cli -g
  build:
    commands:
      - redoc-cli bundle http://petstore.swagger.io/v2/swagger.json
artifacts:
  files:
    - redoc-static.html