version: 0.2
phases:
  install: 
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install redoc-cli -g
  build:
    commands:
      - 'redoc-cli bundle telephant-api-documentation.yml --options "{\"theme\":{\"colors\":{\"primary\":{\"main\":\"#EA6B27\"}},\"sidebar\":{\"background-color\":\"#FF0000\"},\"logo\":{\"gutter\":\"0px\",\"max-width\":\"417px\",\"max-height\":\"190px\"},\"right-panel\":{\"background-color\":\"#A9A9A9\"}}}" --output index.html'
artifacts:
  files:
    - index.html
    - telephant-api-documentation.yml
    - telephant-documentation-logo.jpg
  discard-paths: yes
